#Custom layers


In [3]:
import tensorflow as tf

from tensorflow import keras

class Linear(keras.layers.Layer):
 def __init__(self, units=32,input_dim=32):
  super(Linear, self).__init__()
  self.units = units
  #x_output = W*input +b
  w_init = tf.random_normal_initializer()
  self.w = tf.Variable(initial_value= w_init(shape=(input_dim,units),
                       dtype='float32'), 
                       trainable=True)
  b_init = tf.zeros_initializer()
  self.b = tf.Variable(initial_value= b_init(shape=(units),
                       dtype='float32'), 
                       trainable=True)
 def call (self, inputs):
  return tf.matmul(inputs,self.w)+ self.b
 

x = tf.ones((2,2))
linear_layer = Linear(4,2)
y= linear_layer(x)
  
y


2023-05-10 12:56:08.359809: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-10 12:56:09.527895: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-05-10 12:56:11.465241: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-10 12:56:11.631783: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-10 12:56:11.631847: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_exec

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.00386332, -0.0395805 , -0.0519083 ,  0.09420031],
       [ 0.00386332, -0.0395805 , -0.0519083 ,  0.09420031]],
      dtype=float32)>

In [4]:
linear_layer.weights

[<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.0280527 , -0.02730049, -0.045333  ,  0.03971083],
        [ 0.03191602, -0.01228001, -0.0065753 ,  0.05448948]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [5]:
linear_layer.w

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.0280527 , -0.02730049, -0.045333  ,  0.03971083],
       [ 0.03191602, -0.01228001, -0.0065753 ,  0.05448948]],
      dtype=float32)>

In [6]:
linear_layer.b

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [7]:
class Linear(keras.layers.Layer):
 def __init__(self, units=32):
  super(Linear, self).__init__()
  self.units = units
 
 def build (self, input_shape):
  #x_output  - w*input+b
  w_init = tf.random_normal_initializer()
  self.w = tf.Variable(initial_value=w_init(shape=(input_shape[-1], self.units),dtype='float32'),trainable=True)
  b_init = tf.zeros_initializer()
  self.b= tf.Variable(initial_value=b_init(shape=(self.units),dtype='float32'),trainable=True)
 def call(self,inputs):
  return tf.matmul(inputs,self.w)+self.b
  

In [8]:
linear_layer = Linear(32)

y = linear_layer(x)
y

<tf.Tensor: shape=(2, 32), dtype=float32, numpy=
array([[-0.02004499, -0.0234305 , -0.06891655,  0.03435662, -0.04713523,
         0.1287213 , -0.02922139, -0.05122594, -0.01849775,  0.01359283,
         0.0389331 ,  0.10808773, -0.04169225,  0.00024107, -0.03613696,
         0.04782311,  0.01351454, -0.03063445, -0.10211923,  0.06917837,
        -0.01689867, -0.04370299,  0.04687902,  0.10799699, -0.00135268,
         0.08562245, -0.04749312, -0.05368543,  0.05826339,  0.00088031,
        -0.08060438, -0.05515014],
       [-0.02004499, -0.0234305 , -0.06891655,  0.03435662, -0.04713523,
         0.1287213 , -0.02922139, -0.05122594, -0.01849775,  0.01359283,
         0.0389331 ,  0.10808773, -0.04169225,  0.00024107, -0.03613696,
         0.04782311,  0.01351454, -0.03063445, -0.10211923,  0.06917837,
        -0.01689867, -0.04370299,  0.04687902,  0.10799699, -0.00135268,
         0.08562245, -0.04749312, -0.05368543,  0.05826339,  0.00088031,
        -0.08060438, -0.05515014]], dtyp

In [9]:
class MLPlayer(keras.layers.Layer):
 def __init__(self):
  super(MLPlayer, self).__init__()
  self.linear_1 = Linear(32)
  self.linear_2 = Linear(32)
  self.linear_3 = Linear(100)
 
 def call(self, inputs):
  x = self.linear_1(inputs)
  x = tf.nn.relu(x)
  x = self.linear_2(inputs)
  x = tf.nn.relu(x)
  
  return x

mlp = MLPlayer()
y = mlp(x)
y

<tf.Tensor: shape=(2, 32), dtype=float32, numpy=
array([[0.        , 0.00386941, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01453568, 0.01917745, 0.        ,
        0.08600904, 0.07803933, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.08099713, 0.        , 0.02032595,
        0.        , 0.11093108, 0.        , 0.05489663, 0.        ,
        0.03640718, 0.        ],
       [0.        , 0.00386941, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01453568, 0.01917745, 0.        ,
        0.08600904, 0.07803933, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.08099713, 0.        , 0.02032595,
        0.        , 0.11093108, 0.        , 0.05489663, 0.        ,
        0.03640718, 0.        ]], dtype=float32)>

In [12]:
# Suclassing Model
#custom Models
def normalize_grayscale(image_data):
 a = 0.1
 b = 0.9
 image_data_min = image_data.min()
 image_data_max = image_data.max()
 return a + (b-a)/(image_data_max-image_data_min)*(image_data-image_data_min)

class MinisModel(keras.Model):
 def __init__(self,number_class= 10):
  super(MinisModel,self).__init__()
  self.number_class = number_class
  
  self.flatten_1 = keras.layers.Flatten()
  self.dropout = keras.layers.Dropout(0.1)
  self.dense_1 = keras.layers.Dense(50,activation='relu')
  self.dense_2 = keras.layers.Dense(number_class,activation='softmax')
  
 def call(self,inputs,training=False):
  x = self.flatten_1(inputs)
  x = self.dense_1(x)
  if training:
   x = self.dropout(x,training=training)
  x = self.dense_2(x)
  return x
 
 
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
train_feature = normalize_grayscale(x_train)
test_feature = normalize_grayscale(x_test)

mymnismodel = MinisModel(1)
mymnismodel.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])
mymnismodel.fit(train_feature,y_train,validation_data=(test_feature,y_test),epochs=10)
 